// AUTO-GENERATED by scripts/gen-schema-doc.ts — do not edit by hand.
// Regenerate with: pnpm ai:schema-doc
// Covers 35 tables (the ALLOWED_TABLES allowlist).

export const SCHEMA_DOC_GENERATED = `## account_balances
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  account_id varchar(36) NOT NULL
  currency varchar(3) NOT NULL
  balance numeric(14, 4) NOT NULL
  frozen numeric(14, 4) NOT NULL
  updated_at timestamp NOT NULL

## accounts
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  type varchar(10) NOT NULL
  register_id varchar(36)
  store_id varchar(36)
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## branch_stock
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36) NOT NULL
  branch_id varchar(36) NOT NULL
  quantity double precision NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## branches
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  address varchar(500)
  is_default boolean NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## brands
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## cash_movements
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  shift_id varchar(36) NOT NULL
  register_id varchar(36)
  type varchar(10) NOT NULL
  is_cash boolean NOT NULL
  amount numeric(12, 2) NOT NULL
  currency varchar(3) NOT NULL
  category_id varchar(36)
  category_name varchar(100)
  reason varchar(500)
  cashier_id varchar(36)
  cashier_name varchar(255)
  created_at timestamp NOT NULL

## cash_operation_categories
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(100) NOT NULL
  direction varchar(10) NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL

## cash_registers
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  store_id varchar(36)
  branch_id varchar(36)
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## cash_shifts
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  register_id varchar(36) NOT NULL
  register_name varchar(255)
  status varchar(10) NOT NULL
  opening_float numeric(12, 2) NOT NULL
  usd_rate numeric(12, 4)
  opened_by_cashier_id varchar(36)
  opened_by_cashier_name varchar(255)
  closed_by_cashier_id varchar(36)
  closed_by_cashier_name varchar(255)
  counted_cash numeric(12, 2)
  expected_cash numeric(12, 2)
  cash_in numeric(12, 2)
  cash_out numeric(12, 2)
  difference numeric(12, 2)
  reconciliation jsonb
  order_count integer
  note varchar(500)
  opened_at timestamp NOT NULL
  closed_at timestamp
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## categories
  id varchar(100) NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  image varchar(500)
  is_deleted boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## debt_payments
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  debt_id varchar(36) NOT NULL
  amount numeric(10, 2) NOT NULL
  method varchar(20) NOT NULL
  note varchar(500)
  created_at timestamp NOT NULL

## financial_categories
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  kind varchar(10) NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL

## financial_transactions
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  kind varchar(12) NOT NULL
  account_id varchar(36)
  account_name varchar(255)
  to_account_id varchar(36)
  to_account_name varchar(255)
  is_cash boolean NOT NULL
  amount numeric(14, 4) NOT NULL
  currency varchar(3) NOT NULL
  to_amount numeric(14, 4)
  to_currency varchar(3)
  rate numeric(14, 4)
  subtype varchar(12)
  category_id varchar(36)
  category_name varchar(255)
  cashier_id varchar(36)
  cashier_name varchar(255)
  note varchar(500)
  operation_date timestamp
  order_id varchar(36)
  shift_id varchar(36)
  cash_movement_id varchar(36)
  created_at timestamp NOT NULL

## goods_receipt_items
  id varchar(36) PK NOT NULL
  receipt_id varchar(36) NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36)
  product_name varchar(255) NOT NULL
  price_in numeric(10, 2) NOT NULL
  currency varchar(3) NOT NULL
  price_out numeric(10, 2)
  price_wholesale numeric(10, 2)
  price_bundle numeric(10, 2)
  quantity double precision NOT NULL
  line_total numeric(12, 2) NOT NULL
  created_at timestamp NOT NULL

## goods_receipts
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  supplier_id varchar(36)
  supplier_name varchar(255)
  branch_id varchar(36)
  status varchar(20) NOT NULL
  total_amount numeric(12, 2) NOT NULL
  paid_amount numeric(12, 2) NOT NULL
  returned_amount numeric(12, 2) NOT NULL
  payment_status varchar(10) NOT NULL
  currency varchar(3) NOT NULL
  usd_rate numeric(12, 4)
  item_count integer NOT NULL
  note varchar(500)
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## inventory_batches
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36) NOT NULL
  receipt_item_id varchar(36)
  branch_id varchar(36)
  price_in numeric(10, 2) NOT NULL
  price_out numeric(10, 2) NOT NULL
  qty_received double precision NOT NULL
  qty_remaining double precision NOT NULL
  created_at timestamp NOT NULL

## loyalty_transactions
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  user_id varchar(36) NOT NULL
  order_id varchar(36)
  type varchar(16) NOT NULL
  amount numeric(14, 2) NOT NULL
  balance_after numeric(14, 2) NOT NULL
  note varchar(255)
  created_at timestamp NOT NULL

## monthly_targets
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  month varchar(7) NOT NULL
  revenue_target numeric(14, 2) NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## order_items
  id varchar(36) PK NOT NULL
  order_id varchar(36) NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36)
  product_name varchar(255) NOT NULL
  price_out numeric(10, 2) NOT NULL
  price_type varchar(20) NOT NULL
  quantity double precision NOT NULL
  line_total numeric(12, 2) NOT NULL
  cost_in numeric(10, 2) NOT NULL
  cost_total numeric(12, 2) NOT NULL
  created_at timestamp NOT NULL

## orders
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  client_id varchar(36)
  user_id varchar(36)
  customer_name varchar(255)
  customer_phone varchar(32)
  telegram_user_id varchar(32)
  status varchar(20) NOT NULL
  total_amount numeric(12, 2) NOT NULL
  subtotal_amount numeric(12, 2) NOT NULL
  discount_type varchar(10)
  discount_value numeric(12, 2)
  discount_amount numeric(12, 2) NOT NULL
  loyalty_redeemed numeric(12, 2) NOT NULL
  item_count integer NOT NULL
  payment_method varchar(50)
  payments jsonb
  amount_paid numeric(12, 2)
  change_amount numeric(12, 2)
  tax_rate numeric(5, 2)
  tax_amount numeric(12, 2)
  note varchar(500)
  source varchar(20) NOT NULL
  cashier_id varchar(36)
  cashier_name varchar(255)
  shift_id varchar(36)
  branch_id varchar(36)
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## payment_methods
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  code varchar(50) NOT NULL
  name varchar(100) NOT NULL
  type varchar(10) NOT NULL
  is_visible boolean NOT NULL
  sort_order integer NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## payroll_entries
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  staff_id varchar(36) NOT NULL
  staff_name varchar(255) NOT NULL
  type varchar(12) NOT NULL
  amount numeric(14, 2) NOT NULL
  balance_after numeric(14, 2) NOT NULL
  period_month varchar(7)
  base_amount numeric(14, 2)
  sales_amount numeric(14, 2)
  sales_base numeric(14, 2)
  percent_applied numeric(6, 3)
  account_id varchar(36)
  financial_transaction_id varchar(36)
  note varchar(500)
  created_by_id varchar(36)
  created_by_name varchar(255)
  created_at timestamp NOT NULL

## products
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  code varchar(100)
  barcode varchar(100)
  price_in numeric(10, 2) NOT NULL
  price_out numeric(10, 2) NOT NULL
  price_wholesale numeric(10, 2)
  price_bundle numeric(10, 2)
  quantity double precision NOT NULL
  quantity_type varchar(50)
  unit_id varchar(36)
  image varchar(500)
  category_id varchar(100)
  low_stock_threshold double precision
  brand_id varchar(36)
  supplier_id varchar(36)
  branch_id varchar(36)
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## staff
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  role_id varchar(36)
  name varchar(255) NOT NULL
  login varchar(100)
  password varchar(255)
  has_account boolean NOT NULL
  avatar_url varchar(500)
  position varchar(100)
  phone varchar(32)
  branch_id varchar(36)
  hired_at timestamp
  salary_type varchar(10) NOT NULL
  base_salary numeric(14, 2) NOT NULL
  sales_percent numeric(6, 3) NOT NULL
  percent_base varchar(10) NOT NULL
  salary_balance numeric(14, 2) NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## stock_take_items
  id varchar(36) PK NOT NULL
  stock_take_id varchar(36) NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36)
  product_name varchar(255) NOT NULL
  book_qty double precision NOT NULL
  counted_qty double precision NOT NULL
  diff_qty double precision NOT NULL
  unit_cost numeric(10, 2)
  diff_value numeric(12, 2)
  reason varchar(255)
  checked boolean NOT NULL
  created_at timestamp NOT NULL

## stock_takes
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  store_id varchar(36)
  type varchar(10) NOT NULL
  status varchar(12) NOT NULL
  surplus_qty numeric(14, 3)
  shortage_qty numeric(14, 3)
  diff_value numeric(14, 2)
  created_by_cashier_id varchar(36)
  created_by_cashier_name varchar(255)
  note varchar(500)
  started_at timestamp NOT NULL
  completed_at timestamp
  created_at timestamp NOT NULL

## stock_transfer_items
  id varchar(36) PK NOT NULL
  transfer_id varchar(36) NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36)
  product_name varchar(255) NOT NULL
  quantity double precision NOT NULL
  unit_cost numeric(10, 2)
  line_total numeric(12, 2) NOT NULL
  created_at timestamp NOT NULL

## stock_transfers
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  from_branch_id varchar(36) NOT NULL
  from_branch_name varchar(255)
  to_branch_id varchar(36) NOT NULL
  to_branch_name varchar(255)
  status varchar(12) NOT NULL
  item_count integer NOT NULL
  total_qty numeric(14, 3) NOT NULL
  total_value numeric(14, 2) NOT NULL
  created_by_cashier_id varchar(36)
  created_by_cashier_name varchar(255)
  note varchar(500)
  created_at timestamp NOT NULL

## supplier_payments
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  receipt_id varchar(36) NOT NULL
  supplier_id varchar(36)
  supplier_name varchar(255)
  amount numeric(12, 2) NOT NULL
  currency varchar(3) NOT NULL
  account_id varchar(36)
  account_name varchar(255)
  financial_transaction_id varchar(36)
  note varchar(500)
  cashier_id varchar(36)
  cashier_name varchar(255)
  paid_at timestamp
  created_at timestamp NOT NULL

## supplier_return_items
  id varchar(36) PK NOT NULL
  return_id varchar(36) NOT NULL
  business_id varchar(36) NOT NULL
  product_id varchar(36)
  product_name varchar(255) NOT NULL
  price_in numeric(10, 2) NOT NULL
  quantity double precision NOT NULL
  line_total numeric(12, 2) NOT NULL
  created_at timestamp NOT NULL

## supplier_returns
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  receipt_id varchar(36) NOT NULL
  supplier_id varchar(36)
  supplier_name varchar(255)
  total_amount numeric(12, 2) NOT NULL
  currency varchar(3) NOT NULL
  item_count integer NOT NULL
  note varchar(500)
  cashier_id varchar(36)
  cashier_name varchar(255)
  created_at timestamp NOT NULL

## suppliers
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  phone varchar(50)
  note varchar(500)
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## units
  id varchar(36) PK NOT NULL
  business_id varchar(36)
  name varchar(100) NOT NULL
  short_name varchar(20) NOT NULL
  precision integer NOT NULL
  is_active boolean NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## user_debts
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  user_id varchar(36) NOT NULL
  order_id varchar(36)
  amount numeric(10, 2) NOT NULL
  status varchar(20) NOT NULL
  due_date timestamp with time zone
  description varchar(500)
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL

## users
  id varchar(36) PK NOT NULL
  business_id varchar(36) NOT NULL
  name varchar(255) NOT NULL
  phone varchar(50) NOT NULL
  email varchar(255)
  address varchar(500)
  is_active boolean NOT NULL
  bonus_balance numeric(14, 2) NOT NULL
  total_spent numeric(14, 2) NOT NULL
  created_at timestamp NOT NULL
  updated_at timestamp NOT NULL`;
