/**
 * Generates the schema description handed to the model for ad-hoc SQL.
 *
 *   pnpm ai:schema-doc
 *
 * Reads the same Drizzle table objects the application uses at runtime, so the
 * generated file cannot drift from schema.ts. Only tables in ALLOWED_TABLES are
 * emitted — the model should not learn that `store_bots` exists.
 *
 * The hand-written half (accounting rules, timezone, type traps) lives in
 * src/ai-sql/schema-doc.notes.ts and is reviewed by humans; none of it is
 * derivable from DDL.
 */
import {writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {getTableConfig} from 'drizzle-orm/pg-core';
import * as schema from '../src/database/schema';
import {ALLOWED_TABLES} from '../src/ai-sql/ai-sql.constants';

interface Emitted {
  name: string;
  lines: string[];
}

function describe(): Emitted[] {
  const out: Emitted[] = [];

  for (const value of Object.values(schema)) {
    let config: ReturnType<typeof getTableConfig>;
    try {
      config = getTableConfig(value as never);
    } catch {
      continue; // not a pgTable (a type export, a relations object, …)
    }

    if (!ALLOWED_TABLES.has(config.name)) continue;

    const lines = config.columns.map((col) => {
      const bits = [`  ${col.name}`, col.getSQLType()];
      if (col.primary) bits.push('PK');
      if (col.notNull) bits.push('NOT NULL');
      return bits.join(' ');
    });

    out.push({name: config.name, lines});
  }

  return out.sort((a, b) => a.name.localeCompare(b.name));
}

const tables = describe();
const body = tables
  .map((t) => `## ${t.name}\n${t.lines.join('\n')}`)
  .join('\n\n');

const file = `// AUTO-GENERATED by scripts/gen-schema-doc.ts — do not edit by hand.
// Regenerate with: pnpm ai:schema-doc
// Covers ${tables.length} tables (the ALLOWED_TABLES allowlist).

export const SCHEMA_DOC_GENERATED = \`${body.replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\`;
`;

const target = join(
  __dirname,
  '..',
  'src',
  'ai-sql',
  'schema-doc.generated.ts',
);
writeFileSync(target, file, 'utf8');
console.log(`Wrote ${tables.length} tables to ${target}`);
